<?php
$lugares_interes = [
    [
        'nombre' => 'Rocher de la Vierge',
        'slug'   => 'rocher-de-la-vierge-biarritz',
        'imagen' => 'rocher-de-la-vierge-biarritz-nouvelle-aquitaine-1.jpg',
        'alt'    => 'Rocher de la Vierge en Biarritz',
        'fuente' => 'biarritz.fr',
        'web_imagen' => 'https://www.biarritz.fr/rocher-de-la-vierge',
        'desc'   => 'Icono de Biarritz: un islote rocoso unido por una pasarela con impresionantes vistas al océano.',
    ],
    [
        'nombre' => 'Grande Plage de Biarritz',
        'slug'   => 'grande-plage-biarritz',
        'imagen' => 'grande-plage-biarritz-nouvelle-aquitaine-1.jpg',
        'alt'    => 'Grande Plage de Biarritz',
        'fuente' => 'biarritz-tourisme.com',
        'web_imagen' => 'https://www.biarritz-tourisme.com/grande-plage',
        'desc'   => 'Playa más famosa de la ciudad, ideal para surf, baños de sol y paseos junto al centro histórico.',
    ],
    [
        'nombre' => 'Faro de Biarritz',
        'slug'   => 'faro-de-biarritz',
        'imagen' => 'faro-biarritz.jpg',
        'alt'    => 'Faro de Biarritz en la Pointe Saint-Martin',
        'fuente' => 'biarritz-tourisme.com',
        'web_imagen' => 'https://www.biarritz-tourisme.com/faro',
        'desc'   => 'Situado en la Pointe Saint-Martin, ofrece una panorámica espectacular de la costa vasco-francesa.',
    ],
    [
        'nombre' => 'Museo del Mar - Aquarium de Biarritz',
        'slug'   => 'museo-del-mar-aquarium-biarritz',
        'imagen' => 'museo-del-mar-biarritz-nouvelle-aquitaine-1.jpg',
        'alt'    => 'Museo del Mar - Aquarium en Biarritz',
        'fuente' => 'biarritz.fr',
        'web_imagen' => 'https://www.biarritz.fr/museo-del-mar-aquarium',
        'desc'   => 'Centro dedicado a la fauna marina del Atlántico con acuarios, exposiciones y vistas al mar.',
    ],
    // Nuevas playas
    [
        'nombre' => 'Playa de la Côte des Basques',
        'slug'   => 'cote-des-basques-biarritz',
        'imagen' => 'cote-des-basques-biarritz-nouvelle-aquitaine-1.jpg',
        'alt'    => 'Playa de la Côte des Basques en Biarritz',
        'fuente' => 'biarritz-tourisme.com',
        'web_imagen' => 'https://www.biarritz-tourisme.com/cote-des-basques',
        'desc'   => 'Playa emblemática para surfistas, con vistas panorámicas y ambiente relajado junto a los acantilados.',
    ],
    [
        'nombre' => 'Playa de Marbella',
        'slug'   => 'plage-marbella-biarritz',
        'imagen' => 'marbella.jpg',
        'alt'    => 'Playa de Marbella en Biarritz',
        'fuente' => 'biarritz-tourisme.com',
        'web_imagen' => 'https://www.biarritz-tourisme.com/marbella',
        'desc'   => 'Pequeña playa tranquila ideal para familias, con arena fina y fácil acceso desde el centro.',
    ],
    [
        'nombre' => 'Playa Port Vieux',
        'slug'   => 'plage-port-vieux-biarritz',
        'imagen' => 'port-vieux.jpg',
        'alt'    => 'Playa Port Vieux en Biarritz',
        'fuente' => 'biarritz-tourisme.com',
        'web_imagen' => 'https://www.biarritz-tourisme.com/port-vieux',
        'desc'   => 'Playa protegida y pintoresca, perfecta para nadar y disfrutar de un entorno familiar en pleno centro.',
    ],
    [
        'nombre' => 'Playa de Milady',
        'slug'   => 'plage-milady-biarritz',
        'imagen' => 'milady.jpg',
        'alt'    => 'Playa de Milady en Biarritz',
        'fuente' => 'biarritz-tourisme.com',
        'web_imagen' => 'https://www.biarritz-tourisme.com/milady',
        'desc'   => 'Amplia playa con zona para familias, parques y pistas de deporte, ideal para un día al aire libre.',
    ],
    [
        'nombre' => 'Playa de Miramar',
        'slug'   => 'plage-miramar-biarritz',
        'imagen' => 'miramar.jpg',
        'alt'    => 'Playa de Miramar en Biarritz',
        'fuente' => 'biarritz-tourisme.com',
        'web_imagen' => 'https://www.biarritz-tourisme.com/miramar',
        'desc'   => 'Pequeña playa familiar cercana al centro, perfecta para bañarse y disfrutar de vistas al mar.',
    ],
];
?>
<?php $parrafo = 'Descubre los rincones más emblemáticos de Biarritz, joya de la costa atlántica francesa.'; ?>
<?php require PATH_RAIZ_ESTRUCTURA_PAGINAS_LOCALIDAD . '/print-cards-lugares-interes.php'; ?>
